### ISSUE TITLE
Docker Script

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/k8-reverse-proxy#17]
This is the task for creating the docker compose script to run the service with the following pieces:
- Squid based reverse Proxy for a specific website.
- Two Way URL rewrite/ with the help of NGINX in front of Squid.
- SSL termination.
- ICAP integration (icap://gw-icap01.westeurope.azurecontainer.io/gw_rebuild)

The script should have the following inputs:
- Original website URL(s) / Client facing URL(s) mapping, example: http://www.example.com => http://www.example.com.gw-demo.com.
- Relevant Digital Certificate(s) and Private key(s).
- ICAP server URL and port.
- Squid policy to send which traffic to the ICAP server, extract from the list of GW supported files.

Take note to tune Squid and NGINX to only accept the relevant traffic, to avoid an open proxy situation.

**Comment by mahnouman** [comment]
Please test out this:
https://github.com/filetrust/k8-reverse-proxy/tree/master/upwork-devs/noureddine-yassin/reverse-proxy-icap

**Comment by MariuszFerdyn** [comment]
I think it can be done without NGINX - see my latest commit or just immediately try this:


 docker run --env PROXY_IN=do.pl --env PROXY_WEB=glasswallsolutions.com --env ICAP_GW=20.54.179.61 -p 443:443 -p 80:80 -it mafamafa/squid-reverseproxy:v04

and you can just open http://do.pl - and you will be redirected to the https.... and rewriting will be done to glasswallsolutions.com
