### ISSUE TITLE
OVA-Release

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/k8-reverse-proxy#18]
Release the completed/tested pieces of the project as a "docker-compose script" to run inside an standard Ubuntu 18.04 server OVA image.
The completed pieces of this project so far are:
- Squid based reverse Proxy for a specific website.
- Two Way URL rewrite/ with the help of NGINX in front of Squid.
- SSL termination.
- ICAP integration (icap://gw-icap01.westeurope.azurecontainer.io/gw_rebuild)

Steps:
- Identify relevant packages and create script to install them on top of a bare Ubuntu Server installation of the mentioned release.
- Integrate the script defined in https://github.com/filetrust/k8-reverse-proxy/issues/17
- Test the scenario,
- Submit a PR to be integrated with the rest of OVA components.

Expect the following OVA file structure (Work in progress):
- <somewhere to save scripts>/<Project-Name>/<Scripts/static files , etc>

**Comment by MariuszFerdyn** [comment]
Simplifying, it is enough to run docker run inside the virtual machine --env PROXY_IN = do.pl --env PROXY_WEB = glasswallsolutions.com --env ICAP_GW = 20.54.179.61 -p 443: 443 -p 80:80 -it mafamafa / squid-reverseproxy: v04

We can do it in rc.local - right?

Or just try to more advanced solution like https://cloud.google.com/container-optimized-os/docs ?
