### ISSUE TITLE
ICAP Service Container

### ISSUE THREAD

**Issue by NourEddineX** [k8-proxy/k8-reverse-proxy#31]
- Including [ICAP service](https://github.com/filetrust/c-icap) docker container in the stack

**Comment by NourEddineX** [comment]
Included in https://github.com/filetrust/k8-reverse-proxy/pull/29

**Comment by mahnouman** [comment]
@Abby595 You are assigned to test the PR for this issue, I will provide you with more information on Sunday.

**Comment by Abby595** [comment]
Test Result Summary: The test result is not conclusive.
I didn't face any errors while executing the steps in the readme.md but there are few things that need clarification:
1. There is a Missing command before cd Release01 which is cd k8-reverse-proxy
![er1](https://user-images.githubusercontent.com/71430578/93707614-7c432a80-fb30-11ea-919e-330190201414.PNG)

  2.The word tweak isn't clear enough, instead you can tell the user to use any text editor to edit the file for e.g: **nano subfilter.sh**.
  3.Is there a reason you used a placeholder in the first edit in subfilter.sh and in gwproxy.env you used a value?
  4.The reason to why the user is editing the file and chaning it by adding URL is not included.
![er2](https://user-images.githubusercontent.com/71430578/93707681-0e4b3300-fb31-11ea-9905-ea124ac31383.PNG)

5.After confirming every container is up there was no functionality testing afterwards.
![er3](https://user-images.githubusercontent.com/71430578/93707957-f379be00-fb32-11ea-88b0-85162d3522f5.PNG)
