### ISSUE TITLE
ICAP integration (ICAPeg)

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-reverse-proxy#4]
Once we have issue #3 implemented (i.e. having a basic reverse proxy setup) implemented, we would proceed with integrating ICAPeg.

The reverse proxy would integrate directly with [ICAPeg](https://github.com/egirna/icapeg).
ICAPeg will integrate with an upstream ICAP server which is connected to WG rebuild engine.

**Comment by mahnouman** [comment]
To be closed, not required any longer.
