### ISSUE TITLE
Implement the reverse proxy for https://file-drop.co.uk

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/k8-reverse-proxy#46]
Implementation of the reverse proxy function against https://file-drop.co.uk

**Comment by NourEddineX** [comment]
I was discussing this task with @naderaly , he will start working on the task, but please note that proxying https://file-drop.co.uk **may** not produce the expected results, since file-drop.co.uk is encoding files to base64 **locally in the browser** before sending it in a JSON XHR request, which may not be handled by the rebuild engine.

**Comment by naderaly** [comment]
I've followed steps in **[reverse-proxy-icap-docker (Release 2)](https://github.com/k8-proxy/k8-reverse-proxy/tree/develop/stable-src)** but with the following tweaking:

![image](https://user-images.githubusercontent.com/58347752/94368100-b9845b00-00e2-11eb-8b34-a2bae4e4419e.png)

- Replace command **git clone --recursive https://github.com/k8-proxy/k8-reverse-proxy** with this command **git clone --single-branch -b develop --recursive https://github.com/k8-proxy/k8-reverse-proxy** , As we are not using the master branch.

- Replace **gwproxy.env** & **subfilter.sh** files with the attached files 

- Open & approve the following domains as they are accessed while upload/download process:

![image](https://user-images.githubusercontent.com/58347752/94368307-ab830a00-00e3-11eb-8fc5-6e45c17c3540.png)

1. [o7ymnow6vf.execute-api.us-west-2.amazonaws.com.glasswall-icap.com](o7ymnow6vf.execute-api.us-west-2.amazonaws.com.glasswall-icap.com)
2. [fglpdf9gf6.execute-api.us-west-2.amazonaws.com.glasswall-icap.com](fglpdf9gf6.execute-api.us-west-2.amazonaws.com.glasswall-icap.com)
3. [8oiyjy8w63.execute-api.us-west-2.amazonaws.com.glasswall-icap.com](8oiyjy8w63.execute-api.us-west-2.amazonaws.com.glasswall-icap.com)

- Updated hosts file with the **ALLOWED_DOMAINS** in **gwproxy.env** file

- The uploaded file is encoded base64 locally in the browser and transferred as JSON XHR request which could be the reason that the file is not rebuilt by I-CAP 

![image](https://user-images.githubusercontent.com/58347752/94368478-8e027000-00e4-11eb-9987-17b39a15d52b.png)

**Comment by mahnouman** [comment]
Hello @naderaly please rerun the test and :

1. Make sure ICAP reqmod is enabled (Beside respmod) so we scan uploaded files, if that did not work.
2. Get us a packet capture of the communication between the proxy and the ICAP server.
