### ISSUE TITLE
gwproxy.env not found while building OVA and AMI

### ISSUE THREAD

**Issue by IslamHeggy** [k8-proxy/k8-reverse-proxy#53]
The responsible pipeline of creating the OVA and AMI is now failing after an accepted PR in this repo.

https://github.com/k8-proxy/k8-reverse-proxy/pull/51 

It's failing because gwproxy.env is moved from the directory and this occurred in the failure of creating the images 
![image](https://user-images.githubusercontent.com/11975703/95777263-1cbae380-0cc6-11eb-841f-29c65683926a.png)

Please list all the updates in a release, So we can adapt our releases repo on the changes that is made here. 

Currently we are using the develop branch in our build and we will be using the master branch in the future and this will result in the pipeline failure.

**Comment by mahnouman** [comment]
Hello, there is no further expectations to build standalone docker images out of this project, but a Kubernetes architecture instead. @pranaysahith please also check before we close this. Thanks

**Comment by pranaysahith** [comment]
#54  should fix this issue.
