### ISSUE TITLE
Create diagram for Reverse proxy project

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-reverse-proxy#7]
1.- Read the introduction to the project: https://github.com/filetrust/k8-reverse-proxy
2.- Listen to this call after minute 19 https://glasswallsolu-qbp1117.slack.com/archives/C018UDBGJKH/p1598883417078500, it contains a good summary of the goals of the project. 
3.- If any technical information is needed, please contact @mahnouman

**Comment by mahnouman** [comment]
I am updating this issue with a example diagram, this project has two major milestone from functionality point of view, which is represented in the below diagram, first one is about a reverse proxy scenario, the second one is expanding phase 1 with ICAP integration.
![image](https://user-images.githubusercontent.com/5932628/91883552-e29d0180-ec84-11ea-9d91-a78ebea0e0da.png)

From deployment point of view, there should be a high level diagram representing the Kubernetes deployment.

**Comment by GINAGC** [comment]
Great @mahnouman, could you please share the original image without the milestones highlights?

**Comment by mahnouman** [comment]
Here you are:

![image](https://user-images.githubusercontent.com/5932628/91970515-0cebcf00-ed18-11ea-9f6d-6bf949e1b426.png)
