### ISSUE TITLE
Migrate documentation

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/k8-reverse-proxy#70]
This repository was used to produce some of the websites, we need to:

1. Check the websites repos and identify if a documentation was submitted for them.
2. Check the documentation, generalize it and propagate it to this parent repository.
3. Test out the procedures mentioned in the documentation

The first repo to check is:

https://github.com/k8-proxy/gp-engineering-website
.

**Comment by naderaly** [comment]
@mahnouman, There's documentation found in https://github.com/k8-proxy/gp-engineering-website repo and also I've tested the installation steps and the implementation. the Documentation seems generalized enough and to the point.
- Is there a directory structure in this parent repo where I should propagate the documentation to?

**Comment by mahnouman** [comment]
@naderaly https://github.com/k8-proxy/gp-engineering-website is using this repo as the parent (This one where the issue is created):
https://github.com/k8-proxy/k8-reverse-proxy
The readme file is here:
https://github.com/k8-proxy/k8-reverse-proxy/blob/develop/stable-src/README.md

The result of the task is an updated readme file at this parent repo.

**Comment by mahnouman** [comment]
@naderaly please also consider updating from: https://github.com/k8-proxy/gp-sharepoint
